# AeroSpace Configuration

# Startup commands
after-login-command = []
after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true

# Normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layout defaults
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Focus behavior
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
# Window focus
alt-h = 'focus left'
ctrl-alt-shift-cmd-h = 'focus left'
alt-j = 'focus down'
ctrl-alt-shift-cmd-j = 'focus down'
alt-k = 'focus up'
ctrl-alt-shift-cmd-k = 'focus up'
alt-l = 'focus right'
ctrl-alt-shift-cmd-l = 'focus right'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Window sizing
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'
alt-equal = 'balance-sizes'

# Layout control
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-space = 'fullscreen'
alt-f = 'layout floating tiling'

# Workspace navigation
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-a = 'workspace A'
alt-b = 'workspace B'
alt-c = 'workspace C'

# Workspace movement
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-a = 'move-node-to-workspace A'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-c = 'move-node-to-workspace C'

# Navigation shortcuts
alt-tab = 'workspace-back-and-forth'
alt-backtick = 'workspace-back-and-forth'

# Additional bindings for workspace switching
ctrl-alt-shift-cmd-1 = 'workspace 1'
ctrl-alt-shift-cmd-2 = 'workspace 2'
ctrl-alt-shift-cmd-3 = 'workspace 3'
ctrl-alt-shift-cmd-4 = 'workspace 4'
ctrl-alt-shift-cmd-5 = 'workspace 5'
ctrl-alt-shift-cmd-6 = 'workspace 6'

# Service mode
alt-shift-semicolon = 'mode service'

# Gap toggle
alt-g = 'exec-and-forget ~/.config/aerospace/toggle-gaps.sh'

# Center window as floating
alt-shift-f = 'exec-and-forget ~/.config/aerospace/center-window.sh'

# Window rules
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.atlassian.trello'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.sublimetext.4'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['move-node-to-workspace 5']

# Floating windows
[[on-window-detected]]
if.window-title-regex-substring = 'Meet -'
run = ['layout floating']

[[on-window-detected]]
if.window-title-regex-substring = 'about:blank'
run = ['layout floating']

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = ['layout floating']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
